steps:
  - name: 'gcr.io/kaniko-project/executor'
    args:
      - '--dockerfile=./build/Dockerfile'
      - '--build-arg=REVISION_ID=${REVISION_ID}'
      - '--build-arg=NGINX_PORT=${_NGINX_PORT}'
      - '--cache=true'
      - '--cache-ttl=24h'
      - '--destination=asia-east1-docker.pkg.dev/${PROJECT_ID}/vue-landing-page-repo/vue-landing-page'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vue-landing-page-service'
      - '--image=asia-east1-docker.pkg.dev/${PROJECT_ID}/vue-landing-page-repo/vue-landing-page'
      - '--region=asia-east1'
      - '--platform=managed'
substitutions:
  _NGINX_PORT: '8080'
